# Generated by Django 4.0.3 on 2022-03-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcopy',
            options={'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
