# Generated by Django 4.0.3 on 2022-03-11 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_bookcopy_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookcopy',
            options={},
        ),
    ]
