# Generated by Django 4.0 on 2022-03-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookcopy_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='due_back',
            field=models.DateField(blank=True, null=True),
        ),
    ]
